version: '3.7'
services:

  mysql-database:
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: project
    ports:
      - 3306
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/mysql

  postgres-database:
    image: postgres
    shm_size: '256mb'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: project
    ports:
      - 5432
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mysql-data: {}
  postgres-data: {}

networks:
  backend: {}
